### ISSUE TITLE
Minor comments/suggestions

### ISSUE THREAD

**Issue by lukewagner** [fitzgen/requirements-for-wasm-debugging-capabilities#1]
Overall looks great, here are a few minor comments/suggestions; feel free to take or leave:
* "Must be queryable without running the debuggee program"
  * Would it make sense to refine this to say something like that this applies to the subset of queries that make sense statically?  Examples of obviously-dynamic queries might be the methods for extracting values from a live frame or the dynamic set of inlined frames (see below)
* General Requirements
  * Perhaps explicitly call out that the format shouldn't be depending on the Web embedding; that one should be able to implement/use the format for non-Web embeddings too?
* Inlined Functions
  * Could we include the interpreter use case here as a form of "dynamic inlining"?  I.e., the set of frames inlined doesn't necessarily need to be a static property of the pc, but there could be a method for deriving the set up inlined frames from the dynamic program state?

**Comment by fitzgen** [comment]
Thanks for the suggestions, Luke! I've added text for the second two points.

Regarding the first point: some properties are certainly dynamic, but we can answer these queries with the steps the debugger must perform to answer those questions, rather than performing the steps directly.

For example, consider the query about the dynamic property "what is the value of the source-level variable `x`?"

* Answering with (say) `42` means that the debuggee program must be running.

* Answering with steps like "to get the value of `x`, load the memory at local `$0` minus sixteen" describes some dynamic property, but despite that doesn't require that the debuggee program is running. These steps can be inspected and manipulated by tools that are not running the debuggee program.

Essentially, you could think it like the difference between

```haskell
value_of_var : Variable -> Value
```

and

```haskell
value_of_var : Variable -> (WasmState -> Value)
```

where the `WasmState -> Value` is expressed in some language that tools can inspect (maybe even wasm itself?).

By using this kind of approach, I think we can always maintain that the debugging capabilities can be accessed regardless whether the debuggee program is running.

What do you think?

**Comment by lukewagner** [comment]
Ah hah, I see what you mean; thanks for the clear example.  Yes, that makes sense.

**Comment by lukewagner** [comment]
Thanks!
